### ISSUE TITLE
Error when using docker build

### ISSUE THREAD

**Issue by jdelrue** [mevdschee/php-crud-api#745]
Following error arises when trying to put a record using the docker build:
```
b'{"code":9999,"message":"Class \\"Tqdev\\\\PhpCrudApi\\\\Controller\\\\ResponseUtils\\" not found"}'
```

It was fixed by adjusting this line in api.php:
![image](https://user-images.githubusercontent.com/1687505/106377595-66772900-639e-11eb-930b-24f75220b1a9.png)

had to add in the ref to responseutils

**Comment by mevdschee** [comment]
Hi Jonas, Thank you for reporting this issue. I fixed this and released again. I'll investigate how this failed to show up on the automated tests. Kind regards, Maurits

**Comment by mevdschee** [comment]
Hi Jonas, I think I understand how the bug passed the automated tests. This happened in debug mode when using a non-compiled version, right? Kind regards, Maurits

**Comment by jdelrue** [comment]
I just used the latest docker image

```
  webserver:
        image: mevdschee/php-crud-api
        environment:
        - PHP_CRUD_API_DRIVER=mysql
        - PHP_CRUD_API_ADDRESS=mysqldb
        - PHP_CRUD_API_PORT=3306
        - PHP_CRUD_API_DATABASE=datastore
        - PHP_CRUD_API_USERNAME=root
        - PHP_CRUD_API_PASSWORD=secret
        - PHP_CRUD_API_DEBUG=1
        depends_on:
          - mysqldb
        networks:
          - proxy
```

Debug was indeed enabled, does this affect the bug?
