### ISSUE TITLE
Table not found with sqlite driver

### ISSUE THREAD

**Issue by frugan-it** [mevdschee/php-crud-api#822]
Hi there,

i am trying to use sqlite driver with this sample database https://github.com/mevdschee/php-crud-api/blob/main/tests/fixtures/blog.sqlite , but i always get this error calling the url ```http://domain.tld/api.php/records/categories```:

```
{"code":1001,"message":"Table 'categories' not found"}
```

Via adminer (with [this plugin](https://github.com/FrancoisCapon/LoginToASqlite3DatabaseWithoutCredentialsWithAdminer)) or via php pdo I have no problem querying the sqlite database.
I also tried to use other sqlite databases.

These are the configurations used on my `api.php` (v2.13.0):

```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'database' => '/sqlite-data/blog.sqlite',
'debug' => true,
```

I am using these Docker images:

- https://hub.docker.com/_/nginx (latest)
- https://hub.docker.com/r/bitnami/php-fpm/ (7.4-prod)

These are some interesting parts of the file `docker-compose.yml`:

```yml
version: '3.9'

services:
  nginx:
    volumes:
      - ${PWD}/app:/app

  php-fpm:
    volumes:
      - ${PWD}/app:/app
      - sqlite-data:/sqlite-data:rw

  adminer:
    volumes:
      - ${PWD}/sys/adminer/plugins-enabled:/var/www/html/plugins-enabled
      - sqlite-data:/sqlite-data:rw

volumes:
  sqlite-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/sys/sqlite/data
```

These are the interesting parts of the nginx configuration:

```
server {
    listen [::]:80;
    listen 80;

    server_name _;

    root /app/public;

    index index.php;

    location ~ /\. {
        deny all;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

These are some interesting settings obtained from phpinfo:

```
System | Linux c5010fc92afb 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64

Server API | FPM/FastCGI

Configure Command | '/bitnami/blacksmith-sandox/php-7.4.24/configure' '--prefix=/opt/bitnami/php' '--with-imap=/bitnami/blacksmith-sandox/imap-2007.0.0' '--with-imap-ssl' '--with-zlib-dir' '--with-zlib' '--with-libxml-dir=/usr' '--enable-soap' '--disable-rpath' '--enable-inline-optimization' '--with-bz2' '--enable-sockets' '--enable-pcntl' '--enable-exif' '--enable-bcmath' '--with-pdo-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-png-dir=/usr' '--with-openssl' '--with-libdir=/lib/x86_64-linux-gnu' '--enable-ftp' '--enable-calendar' '--with-gettext' '--with-xmlrpc' '--with-xsl' '--enable-fpm' '--with-fpm-user=daemon' '--with-fpm-group=daemon' '--enable-mbstring' '--enable-cgi' '--enable-ctype' '--enable-session' '--enable-mysqlnd' '--enable-intl' '--with-iconv' '--with-pdo_sqlite' '--with-sqlite3' '--with-readline' '--with-gmp' '--with-curl' '--with-pdo-pgsql=shared' '--with-pgsql=shared' '--with-config-file-scan-dir=/opt/bitnami/php/etc/conf.d' '--enable-simplexml' '--with-sodium' '--enable-gd' '--with-pear' '--with-freetype' '--with-jpeg' '--with-webp' '--with-zip' '--with-pdo-dblib=shared' '--with-tidy' '--with-ldap=/usr/' '--enable-apcu=shared' 'PKG_CONFIG_PATH=/opt/bitnami/common/lib/pkgconfig'

PDO drivers | enabled -> sqlite, mysql

SQLite Library | enabled -> 3.27.2

sqlite3.defensive | Local Value -> 1 | Master Value -> 1

sqlite3.extension_dir | Local Value -> no value | Master Value -> no value

SQLite 3.x driver for PDO | Wez Furlong

SQLite3 | Scott MacVicar, Ilia Alshanetsky, Brad Dewar
```

**Comment by frugan-it** [comment]
I did further tests..

1\) I tried to use also these [php tags](https://hub.docker.com/r/bitnami/php-fpm/tags), but nothing changes:

```
7.1-prod
7.2-prod
7.3-prod
```

2\) If I try to bypass [this method](https://github.com/mevdschee/php-crud-api/blob/main/src/Tqdev/PhpCrudApi/Record/RecordService.php#L51) (`return true`) the error becomes:

```
{"code":9999,"message":"SQLSTATE[HY000]: General error: 1 near \"FROM\": s
```

3\) If I print the value of [this $sql variable](https://github.com/mevdschee/php-crud-api/blob/main/src/Tqdev/PhpCrudApi/Database/GenericDB.php#L278), I get:

```
string(24) "SELECT  FROM "countries""
```

where in practice the variable `$selectColumns` is empty.

**Comment by mevdschee** [comment]
Could it be that the sqlite database file has no read permissions for the PHP user?

**Comment by frugan-it** [comment]
Thanks @mevdschee, to be "safe" I ran this on host machine:

```sh
chmod -Rf 777 ${PWD}/sys/sqlite/data
```
The database is in the correct location, in fact if I call this url `http://domain.tld/test.php`, where `test.php` is:

```php
<?php

try {
    $pdo = new \PDO('sqlite:/sqlite-data/blog.sqlite');

    $stmt = $pdo->query("SELECT * FROM categories");

    $rows = [];
    while ($row = $stmt->fetchObject()) {
        $rows[] = $row;
    }

    var_dump($rows);
} catch (\PDOException $e) {
    var_dump($e->getMessage());
}
```
I get:

```
array(2) { [0]=> object(stdClass)#3 (3) { ["id"]=> string(1) "1" ["name"]=> string(12) "announcement" ["icon"]=> NULL } [1]=> object(stdClass)#4 (3) { ["id"]=> string(1) "2" ["name"]=> string(7) "article" ["icon"]=> NULL } }
```

**Comment by mevdschee** [comment]
I have found it. The documentation states:

>"address": Hostname (or filename) of the database server (localhost)

This is the subtle hint that you should use address instead of database.

Kind regards, Maurits

**Comment by frugan-it** [comment]
Thanks @mevdschee , I tried your valuable suggestion, but unfortunately it doesn't solve the problem.. :confused:

Url: `http://domain.tld/api.php/records/categories`

Inside php-fpm container:

```
root@307234400afa:/# ls -la /sqlite-data/
drwxrwxrwx 2 daemon daemon   4096 Nov  4 10:43 .
drwxr-xr-x 1 daemon    998   4096 Nov  4 13:22 ..
-rwxrwxrwx 1 daemon daemon     50 Nov  2 14:52 .gitignore
-rwxrwxrwx 1 daemon daemon 106496 Nov  4 10:43 blog.sqlite
```

1\) 
```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => '/sqlite-data/blog.sqlite',
'database' => '',
'debug' => true,
```
Output:
```
{"code":1001,"message":"Table 'categories' not found"}
```

2\) 
```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => 'sqlite',
'database' => '/sqlite-data/blog.sqlite',
'debug' => true,
```
Output:
```
{"code":1001,"message":"Table 'categories' not found"}
```

3\) 
```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => '',
'database' => 'sqlite:/sqlite-data/blog.sqlite',
'debug' => true,
```
Output:
```
{"code":1001,"message":"Table 'categories' not found"}
```

4\) 
```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => 'sqlite:/sqlite-data',
'database' => 'blog.sqlite',
'debug' => true,
```
Output:
```
{"code":1001,"message":"Table 'categories' not found"}
```

5\) 
```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => 'sqlite:/sqlite-data/',
'database' => 'blog.sqlite',
'debug' => true,
```
Output:
```
{"code":1001,"message":"Table 'categories' not found"}
```

6\) 
```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => 'sqlite:/sqlite-data/blog.sqlite',
'database' => '',
'debug' => true,
```
Output:
```
{"code":9999,"message":"open_basedir prohibits opening sqlite:\/sqlite-data\/blog.sqlite"}
```

7\) 
```
cp -a /sqlite-data/blog.sqlite /app/public
```

```php
'driver' => 'sqlite',
'username' => '',
'password' => '',
'address' => 'sqlite:/app/public/blog.sqlite',
'database' => '',
'debug' => true,
```
Output:
```
{"code":9999,"message":"open_basedir prohibits opening sqlite:\/app\/public\/blog.sqlite"}
```

**Comment by mevdschee** [comment]
I think option 1 is correct, see:

        private function getDsn(): string
        {
            switch ($this->driver) {
                case 'mysql':
                    return "$this->driver:host=$this->address;port=$this->port;dbname=$this->database;charset=utf8mb4";
                case 'pgsql':
                    return "$this->driver:host=$this->address port=$this->port dbname=$this->database options='--client_encoding=UTF8'";
                case 'sqlsrv':
                    return "$this->driver:Server=$this->address,$this->port;Database=$this->database";
                case 'sqlite':
                    return "$this->driver:$this->address";
            }
        }

**Comment by frugan-it** [comment]
Thanks @mevdschee, I think I have found the source of the problem..

Url (1) (2) (3) (4) (5)
```
http://localhost:8080/api.php/records/categories
```
Tree (1) (2) (3) (4) (5)
```
|____public
| |____.htaccess
| |____blog.sqlite
| |____api.php
|____docker-compose.yml
```
.htaccess (1) (2) (3) (4) (5)
```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ api.php/$1 [QSA,L]
</IfModule>
```
docker-compose.yml (1) (2)
```
version: '3.9'

services:

  php-crud-api:
    image: php:apache
    networks:
      - network
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/public:/var/www/html
    environment:
      PHP_CRUD_API_DRIVER: 'sqlite'
      PHP_CRUD_API_ADDRESS: '/var/www/html/blog.sqlite'
      PHP_CRUD_API_DATABASE: 
      PHP_CRUD_API_USERNAME: 
      PHP_CRUD_API_PASSWORD: 
      PHP_CRUD_API_DEBUG: 1

networks:
  network:
```
docker-compose.yml (3)
```
version: '3.9'

services:

  php-crud-api:
    image: php:apache
    networks:
      - network
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/public:/var/www/html
    environment:
      PHP_CRUD_API_DRIVER: 'sqlite'
      PHP_CRUD_API_ADDRESS: '/var/www/html/blog.sqlite'
      PHP_CRUD_API_DATABASE: '/var/www/html/blog.sqlite'
      PHP_CRUD_API_USERNAME: 
      PHP_CRUD_API_PASSWORD: 
      PHP_CRUD_API_DEBUG: 1

networks:
  network:
```
docker-compose.yml (4) (5)
```
version: '3.9'

services:

  php-crud-api:
    image: php:apache
    networks:
      - network
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/public:/var/www/html

networks:
  network:
```
api.php v2.13.0 (1)
```
'username' => '',
'password' => '',
'database' => 'php-crud-api', // <-- fake value
```
api.php v2.13.0 (2) (3)
```
'username' => '',
'password' => '',
'database' => '', // <-- empty value
```
api.php v2.13.0 (4)
```
'driver' => 'sqlite',
'address' => '/var/www/html/blog.sqlite',
'username' => '',
'password' => '',
'database' => '', // <-- empty value
'debug' => true,
```
api.php v2.13.0 (5)
```
'driver' => 'sqlite',
'address' => '/var/www/html/blog.sqlite',
'username' => '',
'password' => '',
'database' => '/var/www/html/blog.sqlite', // <-- also needed here
'debug' => true,
```
Output (1) (3) (5)
```
{"records":[{"id":1,"name":"announcement","icon":null},{"id":2,"name":"article","icon":null},{"id":3,"name":"comment","icon":null}]}
```
Output (2) (4)
```
{"code":1001,"message":"Table 'categories' not found"}
```
