### ISSUE TITLE
swagger docker-compose instant openapi

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#989]
working on a project I prepared a docker-compose file to put up mysql, php, and swagger to work straight away on the php-crud-api endpoint.

this is what I ended up with:
docker-compose.yml
```
version: "3.9"
services:
  swagger:
    container_name: php-crud-api-swagger
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON_URL: <url_to_php_crud_api_endpoint>
      DOC_EXPANSION: none # optionally set to list, or full

```

I've also have a repo available involving mysql, nginx, php-fpm and swagger to be up and running in seconds
